// Code generated by 'yaegi extract github.com/calebhiebert/xo/templates/yamltpl'. DO NOT EDIT.

package internal

import (
	"github.com/calebhiebert/xo/templates/yamltpl"
	"reflect"
)

func init() {
	Symbols["github.com/calebhiebert/xo/templates/yamltpl/yamltpl"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Files": reflect.ValueOf(&yamltpl.Files).Elem(),
	}
}
